//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RakutenDrive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RakutenDrive.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Copyright 2025 Rakuten Drive
        ///Rakuten Symphony Korea, Inc..
        /// </summary>
        public static string about_window_copyright {
            get {
                return ResourceManager.GetString("about-window/copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string about_window_version {
            get {
                return ResourceManager.GetString("about-window/version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login credentials have changed or expired. Please re-login to continue using Rakuten Drive..
        /// </summary>
        public static string error_force_logout_message {
            get {
                return ResourceManager.GetString("error/force-logout-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string error_force_logout_title {
            get {
                return ResourceManager.GetString("error/force-logout-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later. .
        /// </summary>
        public static string error_general_message {
            get {
                return ResourceManager.GetString("error/general-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete.
        /// </summary>
        public static string error_general_title_delete {
            get {
                return ResourceManager.GetString("error/general-title-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Download.
        /// </summary>
        public static string error_general_title_download {
            get {
                return ResourceManager.GetString("error/general-title-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Move.
        /// </summary>
        public static string error_general_title_move {
            get {
                return ResourceManager.GetString("error/general-title-move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Rename.
        /// </summary>
        public static string error_general_title_rename {
            get {
                return ResourceManager.GetString("error/general-title-rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item already exists.
        /// </summary>
        public static string error_item_already_exists {
            get {
                return ResourceManager.GetString("error/item-already-exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission .
        /// </summary>
        public static string error_item_no_permission {
            get {
                return ResourceManager.GetString("error/item-no-permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error syncing to cloud .
        /// </summary>
        public static string error_item_sync_error {
            get {
                return ResourceManager.GetString("error/item-sync-error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to delete this item &quot;{0}&quot;. The deleted item will sync back after some time..
        /// </summary>
        public static string error_no_permission_message_delete {
            get {
                return ResourceManager.GetString("error/no-permission-message-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to download the file. Please log in to Rakuten Drive Web to view it or contact your admin to request permission.&quot;.
        /// </summary>
        public static string error_no_permission_message_download {
            get {
                return ResourceManager.GetString("error/no-permission-message-download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to move this item &quot;{0}&quot;..
        /// </summary>
        public static string error_no_permission_message_move {
            get {
                return ResourceManager.GetString("error/no-permission-message-move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to rename this item &quot;{0}&quot;..
        /// </summary>
        public static string error_no_permission_message_rename {
            get {
                return ResourceManager.GetString("error/no-permission-message-rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string error_no_permission_title {
            get {
                return ResourceManager.GetString("error/no-permission-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affordable, convenient and secure cloud storage that enhances work efficiency..
        /// </summary>
        public static string login_window_affordable {
            get {
                return ResourceManager.GetString("login-window/affordable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string login_window_login {
            get {
                return ResourceManager.GetString("login-window/login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized
        ///Cloud Storage for
        ///Businesses.
        /// </summary>
        public static string login_window_optimized {
            get {
                return ResourceManager.GetString("login-window/optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A web browser will open to complete the login..
        /// </summary>
        public static string login_window_web_browser {
            get {
                return ResourceManager.GetString("login-window/web-browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string logout_window_logout {
            get {
                return ResourceManager.GetString("logout-window/logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Rakuten Drive.
        /// </summary>
        public static string menu_about {
            get {
                return ResourceManager.GetString("menu/about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string menu_help_center {
            get {
                return ResourceManager.GetString("menu/help-center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rakuten Drive.
        /// </summary>
        public static string menu_open {
            get {
                return ResourceManager.GetString("menu/open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rakuten Drive In Web.
        /// </summary>
        public static string menu_open_in_web {
            get {
                return ResourceManager.GetString("menu/open-in-web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Rakuten Drive.
        /// </summary>
        public static string menu_quit {
            get {
                return ResourceManager.GetString("menu/quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Drive.
        /// </summary>
        public static string my_drive {
            get {
                return ResourceManager.GetString("my-drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakuten Drive.
        /// </summary>
        public static string rakuten_drive {
            get {
                return ResourceManager.GetString("rakuten-drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Drive.
        /// </summary>
        public static string team_drive {
            get {
                return ResourceManager.GetString("team-drive", resourceCulture);
            }
        }
    }
}
